# This is a basic workflow to help you get started with Actions
# NAME OF THE WORKFLOW
name: CI SMART PROJECT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}   # runs on ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it/ EN GROS RECUPERE TOUTE LES DEPENDENCES AUQUEL TON FICHIER A BESOIN -FONCTIONS DE GITHUB/ACTION
      - uses: actions/checkout@v3
    
      - name: Github Stuff
        run: echo "My Github repo is called ${{github.repository}}"
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  
